### ISSUE TITLE
Error. Not working

### ISSUE THREAD

**Issue by barripdmx** [rinze/nygraph_twitter#2]
Hi,

In the step Run "python get_data.py account_name" present error:

> Traceback (most recent call last):
>   File "get_data.py", line 1, in <module>
>     import twitter
> ImportError: No module named twitter

If change the line 

> import twitter

from

>  from TwitterAPI import TwitterAPI

prensent error:

> Will get followers for barripdmx
> Traceback (most recent call last):
>   File "get_data.py", line 58, in <module>
>     flist = get_follower_list(username)
>   File "get_data.py", line 16, in get_follower_list
>     api = twitter.Api(consumer_key = consumer_key,
> NameError: global name 'twitter' is not defined

I have solution?

Best regards

**Comment by rinze** [comment]
You need to use the proper Twitter library: https://python-twitter.readthedocs.io/en/latest/

**Comment by barripdmx** [comment]
Gracias.
