### ISSUE TITLE
Another problem

### ISSUE THREAD

**Issue by barripdmx** [rinze/nygraph_twitter#3]
I have solution?

>  File "get_data.py", line 47
>     print "\t * Partial user data download failed. Skipping 100 user_ids"
>                                                                         ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\t * Partial user data download failed. Skipping 100 user_ids")?

Gracias.

**Comment by rinze** [comment]
You're using Python 3. I coded the script with Python 2.7. You'll need to edit the code to make it Python 3 compatible (for instance, wrapping all `print` calls with parentheses.)

**Comment by barripdmx** [comment]
Perfecto ;)
