### ISSUE TITLE
Issue when the account has too much followers

### ISSUE THREAD

**Issue by catacri** [rinze/nygraph_twitter#4]
I'm having a problem when I try to apply this code to accounts with ~1 million followers (or more).
My code says:

       raise ConnectionError(err, request=request)
    request.exceptions.ConnectionError: ('Connection Aborted.', error("(10054, 'WSAECONNRESET')",))

Have any had this problem too? Whit accounts with 200-300k followers I'm not having problems.

Thank you!

**Comment by rinze** [comment]
Never happened to me. Looks like a requests issue, closing.
